export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  if (!process.env.ANTHROPIC_API_KEY) {
    return res.status(503).json({ error: 'AI service is not configured yet. Please try again later.' });
  }

  try {
    const {
      disputeType,
      creditorName,
      accountLast4,
      reason,
      disputeReason,
      bureau,
      creditBureau,
      personalDetails,
      additionalContext,
      firstName,
      lastName,
    } = req.body;

    /* Accept field names from both old and new frontends */
    const finalReason = reason || disputeReason;
    const finalBureau = bureau || creditBureau || 'All three bureaus';
    const finalContext = personalDetails || additionalContext;
    const clientName = [firstName, lastName].filter(Boolean).join(' ');

    if (!disputeType || !finalReason) {
      return res.status(400).json({ error: 'Dispute type and reason are required.' });
    }

    const systemPrompt = `You are nueCredit's AI dispute letter specialist. You help consumers draft professional dispute letters to credit bureaus under their rights granted by the Fair Credit Reporting Act (FCRA), specifically Section 611.

Your letters must:
- Be professional, firm, and legally sound
- Reference relevant FCRA sections (Section 611, Section 623 when applicable)
- Include proper formatting: date, bureau address, consumer info, RE line, body, signature
- Request investigation within the legally required 30-day window
- Request deletion or correction of disputed items
- Include a statement about providing documentation if needed
- If the client's name is provided, use it in the letter (for salutation and signature). For any other personal info not provided (address, SSN last 4, date of birth), use placeholders like [YOUR ADDRESS], [SSN LAST 4], [DATE OF BIRTH]
- Never provide legal advice — frame as the consumer exercising their rights

Available bureaus and addresses:
- Equifax: P.O. Box 740256, Atlanta, GA 30374
- Experian: P.O. Box 4500, Allen, TX 75013
- TransUnion: P.O. Box 2000, Chester, PA 19016

You MUST respond with ONLY valid JSON (no markdown, no code fences) with these fields:
- letter: string (the full dispute letter with proper formatting)
- bureau: string (which bureau to send to)
- bureauAddress: string
- filingInstructions: string[] (3-4 step instructions for sending)
- tips: string[] (2-3 helpful tips)
- disclaimer: string (must include "This letter was generated by nueCredit's AI tools. For complex disputes, we recommend working with nueCredit's professional credit restoration team.")`;

    const userPrompt = `Generate a dispute letter with these details:
${clientName ? `- Client name: ${clientName}` : '- Client name: [YOUR NAME]'}
- Dispute type: ${disputeType}
- Creditor/Company name: ${creditorName || 'Not specified'}
- Account last 4 digits: ${accountLast4 || 'N/A'}
- Reason for dispute: ${finalReason}
- Bureau to send to: ${finalBureau}
${finalContext ? `- Additional context: ${finalContext}` : ''}`;

    const aiRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 2048,
        system: systemPrompt,
        messages: [
          { role: 'user', content: userPrompt },
        ],
      }),
    });

    if (!aiRes.ok) {
      const err = await aiRes.text();
      console.error('[AI] Claude error:', err);
      return res.status(502).json({ error: 'AI service temporarily unavailable.' });
    }

    const aiData = await aiRes.json();
    const rawText = aiData.content[0].text;
    const result = JSON.parse(rawText);

    return res.status(200).json({
      success: true,
      disputeType,
      ...result,
    });
  } catch (err) {
    console.error('[API /ai/dispute-letter] Error:', err);
    return res.status(500).json({ error: 'Something went wrong. Please try again.' });
  }
}
